### ISSUE TITLE
PG Switch fails with BadRequestException during 'turn_on'

### ISSUE THREAD

**Issue by danddorr** [Pigotka/ha-cc-jablotron-cloud#56]
I am reporting a persistent bug where the PG entity, configured as a switch, has never worked since my initial installation of this custom component several months ago.
​The issue persists across all Home Assistant updates and was not resolved by the Jablotron Cloud integration updates.
​When I attempt to activate the PG switch (turn_on), the API call consistently fails with a BadRequestException. This prevents any control of the PG device via Home Assistant.

**System Details**
Integration: ha-cc-jablotron-cloud (Jablotron Cloud) – Version: 0.7.0
Device: JA100
Entities: 5
Failing command: switch.turn_on
Home Assistant Core: 2025.11.1
Supervisor: 2025.11.1
Operating System: 16.3
Frontend: 20251105.0
Installation method: Home Assistant OS

![Screenshot_20251112_100147_Home Assistant.jpg](https://github.com/user-attachments/assets/8c611750-ad0d-4123-9548-74041da8c070)

**Traceback:**
```
Logger: homeassistant.components.websocket_api.http.connection
Zdroj: components/websocket_api/commands.py:270
Integrácia: Home Assistant WebSocket API (dokumentácia, problémy)
Prvýkrát sa vyskytol: 10. novembra 2025 o 10:31:51 (6 výskytov)
Naposledy prihlásený: 10:06:16

[139941892260704] Unexpected exception
[139941521558400] Unexpected exception
[139941226692448] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 270, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2816, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2859, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 830, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 902, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1674, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/jablotron_cloud/switch.py", line 140, in turn_on
    turn_on_successful = bridge.control_programmable_gate(
        service_id=self._service_id,
    ...<2 lines>...
        state="ON"
    )
  File "/usr/local/lib/python3.13/site-packages/jablotronpy/jablotronpy.py", line 323, in control_programmable_gate
    response = self._send_request(
        endpoint=f"{service_type}/controlComponent.json",
    ...<8 lines>...
        }
    )
  File "/usr/local/lib/python3.13/site-packages/jablotronpy/jablotronpy.py", line 63, in _send_request
    raise BadRequestException("Request is not valid, please review provided parameters.")
jablotronpy.exceptions.BadRequestException: Request is not valid, please review provided parameters.
```

**Comment by Pigotka** [comment]
Will look into it. It was detected as controllable so it should allow you to control it.

**Comment by Pigotka** [comment]
Fixed in #69

**Comment by danddorr** [comment]
Thanks for the fix in #69! Adding `pin_code` support to the integration is a great step. However, after further testing, I found that `BadRequestException` still occurs specifically when using a **5-digit PIN**.

It seems there is an underlying issue with how the payload is formatted or validated in the `jablotronpy` library (v0.7.3) when the PIN exceeds 4 digits. I have opened a detailed issue in the library's repository: https://github.com/fdegier/JablotronPy/issues/36.

While 4-digit PINs likely work now, 5-digit codes are still being rejected by the API with `REQUEST.PARAMETER.INCORRECT-VALUE`.
